#!/usr/bin/env python3
"""Path-stable launcher for MCP clients started from an arbitrary cwd."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from notion_report.config import (  # noqa: E402
    DestinationError,
    DestinationStore,
    SYSTEM_AGENT_ID,
    SYSTEM_PROJECT_SLUG,
)


def _load_scoped_destination_token(
    environ: dict[str, str] | None = None,
    env_file: str | Path | None = None,
) -> bool:
    """Load only the bound destination's token from AgentUI's local env file.

    Codex normally forwards the token through its MCP ``env_vars`` allow-list.
    Resumed Codex sessions have intermittently relaunched stdio MCP without that
    one variable, even though the scoped identity and destination config were
    preserved. This fail-closed fallback reads one exact key from the fixed,
    gitignored AgentUI env file; unscoped or unbound MCP launches receive no
    credential.
    """
    env = environ if environ is not None else os.environ
    project_slug = str(env.get("AGENTUI_PROJECT_SLUG") or "").strip()
    agent_id = str(env.get("AGENTUI_AGENT_ID") or "").strip()
    if not project_slug or not agent_id:
        return False

    config_path = env.get(
        "NOTION_REPORT_CONFIG",
        str(Path(__file__).with_name("destinations.json")),
    )
    try:
        destination = DestinationStore(config_path).resolve(project_slug, agent_id)
    except DestinationError:
        # An unbound project may be provisioned below the one AgentUI System Hub.
        # Forward only that hub's selected credential; the MCP tool still confines
        # the resulting project destination before exposing reads or writes.
        try:
            destination = DestinationStore(config_path).get(
                SYSTEM_PROJECT_SLUG, SYSTEM_AGENT_ID)
        except DestinationError:
            return False
    token_env = destination.token_env
    if str(env.get(token_env) or "").strip():
        return True

    path = Path(env_file) if env_file is not None else REPOSITORY_ROOT / "app" / ".env.local"
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return False
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        key, separator, value = line.partition("=")
        if not separator or key.strip() != token_env:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        if value:
            env[token_env] = value
            return True
        return False
    return False


def _apply_cli_scope(
    argv: list[str] | None = None,
    environ: dict[str, str] | None = None,
) -> None:
    """Bind the MCP identity from secret-free argv, independent of env forwarding."""
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--project")
    parser.add_argument("--agent")
    parser.add_argument("--config")
    parser.add_argument("--project-name")
    parser.add_argument("--project-root-agent")
    parser.add_argument("--project-directory")
    parser.add_argument("--report-schema-file")
    args = parser.parse_args(argv)
    values = (args.project, args.agent, args.config)
    if any(values) and not all(values):
        parser.error("--project, --agent and --config must be provided together")
    if not all(values):
        return
    env = environ if environ is not None else os.environ
    # Command-line scope is generated by AgentUI and intentionally overrides
    # inherited values so a resumed client cannot retain a stale identity.
    env["AGENTUI_PROJECT_SLUG"] = str(args.project)
    env["AGENTUI_AGENT_ID"] = str(args.agent)
    env["NOTION_REPORT_CONFIG"] = str(args.config)
    if args.project_name:
        env["AGENTUI_PROJECT_NAME"] = str(args.project_name)
    if args.project_root_agent:
        env["AGENTUI_PROJECT_ROOT_AGENT_ID"] = str(args.project_root_agent)
    if args.project_directory:
        env["AGENTUI_PROJECT_ROOT"] = str(args.project_directory)
    if args.report_schema_file:
        env["AGENTUI_REPORT_SCHEMA_FILE"] = str(args.report_schema_file)

from notion_report.mcp_server import main  # noqa: E402


if __name__ == "__main__":
    _apply_cli_scope()
    _load_scoped_destination_token()
    main()
